name: Yapi Webapp Smoke Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/webapp-dev.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'cmd/**'
      - 'internal/**'
      - '.github/workflows/webapp-dev.yml'
  workflow_dispatch:

jobs:
  smoke-test:
    name: Validate Homepage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # ------------------------------------------------------------------
      # 1. PREP: Build the site
      # ------------------------------------------------------------------
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install & Build Web
        run: |
          pnpm install --frozen-lockfile
          pnpm --filter madea-blog-core build
          pnpm build:web

      # ------------------------------------------------------------------
      # 1.5. BUILD & INSTALL YAPI CLI
      # ------------------------------------------------------------------
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build & Install Yapi CLI
        run: |
          make build
          sudo cp ./bin/yapi /usr/local/bin/yapi
          yapi version

      # ------------------------------------------------------------------
      # 2. THE FUN PART: Use our Action
      # ------------------------------------------------------------------
      - name: Run Smoke Tests
        # uses: ./action
        uses: jamierpond/yapi/action@v0.5.1
        with:
          # Using locally built yapi!
          version: local

          # The Action handles backgrounding this!
          start: pnpm --filter web start --port 3000

          # The Action handles waiting for this!
          wait-on: http://localhost:3000/healthz

          # The Action runs this once healthy!
          command: yapi test ./web/yapi -a
