yapi: v1
kind: project

defaults_environment: local

environments:
  # Local Development: Point to different localhost ports
  local:
    vars:
      user_host: "http://localhost:3001"
      payment_host: "http://localhost:3002"
      notification_host: "http://localhost:3003"

  # Staging: Point to the cloud staging subdomains
  staging:
    vars:
      user_host: "https://users.staging.api.com"
      payment_host: "https://payments.staging.api.com"
      notification_host: "https://notify.staging.api.com"
